sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '9'
  - '8'
  - '6'
before_install:
  # TODO: Switch this back to yarn when greenkeeperio/greenkeeper-lockfile#98 is fixed.
  # https://github.com/greenkeeperio/greenkeeper-lockfile/issues/98
  - npm install --global greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script: 'yarn install && yarn build && npx semantic-release'
        on:
          branch: master
