sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '7'
  - '6'
  - '4'
before_install:
  # TODO: Switch this back to yarn when greenkeeperio/greenkeeper-lockfile#98 is fixed.
  # https://github.com/greenkeeperio/greenkeeper-lockfile/issues/98
  - npm install --global greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - semantic-release pre && yarn run build && npm publish && semantic-release post
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
