aliases:
  install_dependencies_step: &install_dependencies_step
    run:
      name: install-dependencies
      command: |
        curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm
        pnpm install --frozen-lockfile

  unit_test: &unit_test
    steps:
      - checkout
      - *install_dependencies_step
      - run:
          name: tests
          command: 'pnpm test:ci'
          environment:
            JEST_JUNIT_OUTPUT: 'reports/junit/js-test-results.xml'
      - run:
          name: lint
          command: 'pnpm lint'
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

version: 2
jobs:
  node-v14-latest:
    docker:
      - image: cimg/node:14.19
    <<: *unit_test
  node-v16-latest:
    docker:
      - image: cimg/node:16.15
    <<: *unit_test
  node-v18-latest:
    docker:
      - image: cimg/node:18.3
    <<: *unit_test
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - *install_dependencies_step
      - run:
          name: Publish package
          command: 'pnpm build && npx semantic-release'

workflows:
  version: 2
  test-deploy:
    jobs:
      - node-v14-latest
      - node-v16-latest
      - node-v18-latest
      - deploy:
          requires:
            - node-v14-latest
            - node-v16-latest
            - node-v18-latest
          filters:
            branches:
              only: master
